### ISSUE TITLE
Update issues after revamp

### ISSUE THREAD

**Issue by Andargor** [alinmear/docker-conanexiles#34] opened 2019-01-26 22:17 UTC
Pulled the latest image. A previously working instance is not longer restarting after an update, and the update doesn't seem to be applied.

I tried running the update manually:
```bash
supervisorctl start conanexilesUpdate

2019-01-26 21:59:03,202 INFO spawned: 'conanexilesUpdate' with pid 814
WARNING: setlocale('en_US.UTF-8') failed, using locale: 'C'. International characters may not work.
Redirecting stderr to '/root/Steam/logs/stderr.txt'
[  0%] Checking for available updates...
[----] Verifying installation...
Steam Console Client (c) Valve Corporation
-- type 'quit' to exit --
Loading Steam API...OK.
@sSteamCmdForcePlatformType windows
"@sSteamCmdForcePlatformType" = "windows"

Connecting anonymously to Steam Public...2019-01-26 21:59:05,140 INFO success: conanexilesUpdate entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
Logged in OK
Waiting for user info...OK
force_install_dir /conanexiles
app_update 443030 validate
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x3) reconfiguring, progress: 0.00 (0 / 0)
 Update state (0x5) validating, progress: 11.83 (238513527 / 2016424146)
 Update state (0x5) validating, progress: 27.69 (558373136 / 2016424146)
 Update state (0x5) validating, progress: 46.74 (942411025 / 2016424146)
 Update state (0x5) validating, progress: 66.08 (1332548513 / 2016424146)
 Update state (0x5) validating, progress: 85.33 (1720611043 / 2016424146)
 Update state (0x5) validating, progress: 96.81 (1951999781 / 2016424146)
Success! App '443030' fully installed.
quit
2019-01-26 21:59:21,013 INFO exited: conanexilesUpdate (exit status 0; expected)

...

Warning: Update seems to have failed. Installed build (3488966) does not match available build (3498259).
>> WARN: Failed to connect to redis instance - redis:6379. Skipping redis call: redis_set_update_running_stop
2019-01-26 22:26:34,955 INFO spawned: 'conanexilesServer' with pid 1370
2019-01-26 22:26:35,957 INFO success: conanexilesServer entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
conanexilesServer: started

```

But when I restart the server, it says it's not the latest version:
```bash
>> INFO: New build available. Updating 3488966 -> 3498259
>> WARN: Failed to connect to redis instance - redis:6379. Skipping redis call: redis_set_update_running_start
>> DEBUG: Shutdown Server in 15 minutes

...

2019-01-26 22:21:13,869 INFO waiting for conanexilesServer to stop
2019-01-26 22:21:14,039 INFO stopped: conanexilesServer (terminated by SIGTERM)
conanexilesServer: stopped

```

After every restart, it shuts down like this for an update, but then never actually updates or starts the server.

Docker run command:

```bash
docker run -d -p 7777-7778:7777-7778 -p 7777-7778:7777-7778/udp -p 27000-27015:27000-27015 -p 27000-27015:27000-27015/udp -p 32330:32330 \
-e TZ="America/Montreal" \
-e "CONANEXILES_ServerSettings_ServerSettings_AdminPassword"="XXXX" \
-e "CONANEXILES_ServerSettings_ServerSettings_ServerPassword"="XXXX" \
-e "CONANEXILES_ServerSettings_ServerSettings_HarvestAmountMultiplier"=2 \
-e "CONANEXILES_ServerSettings_ServerSettings_PlayerXPRateMultiplier"=1 \
-e "CONANEXILES_ServerSettings_ServerSettings_ThrallConversionMultiplier"=0.1 \
-e "CONANEXILES_ServerSettings_ServerSettings_ItemConvertionMultiplier"=0.1 \
-e "CONANEXILES_ServerSettings_ServerSettings_PlayerIdleThirstMultiplier"=0.25 \
-e "CONANEXILES_ServerSettings_ServerSettings_PlayerActiveThirstMultiplier"=0.5 \
-e "CONANEXILES_ServerSettings_ServerSettings_PlayerIdleHungerMultiplier"=0.25 \
-e "CONANEXILES_ServerSettings_ServerSettings_PlayerActiveHungerMultiplier"=0.5 \
-e "CONANEXILES_ServerSettings_ServerSettings_DayCycleSpeedScale"=0.25 \
-e "CONANEXILES_ServerSettings_ServerSettings_DayTimeSpeedScale"=0.5 \
-e "CONANEXILES_ServerSettings_ServerSettings_NightTimeSpeedScale"=4.0 \
-e "CONANEXILES_ServerSettings_ServerSettings_LogoutCharactersRemainInTheWorld"="False" \
-e "CONANEXILES_ServerSettings_ServerSettings_DurabilityMultiplier"=2 \
-e "CONANEXILES_ServerSettings_ServerSettings_DropEquipmentOnDeath"="True" \
-e "CONANEXILES_ServerSettings_ServerSettings_EverybodyCanLootCorpse"="True" \
-e "CONANEXILES_ServerSettings_ServerSettings_ItemSpoilRateScale"=1.0 \
-e "CONANEXILES_ServerSettings_ServerSettings_ResourceRespawnSpeedMultiplier"=0.5 \
-e "CONANEXILES_ServerSettings_ServerSettings_ThrallExclusionRadius"=100 \
-e "CONANEXILES_ServerSettings_ServerSettings_UnconsciousTimeSeconds"=3600 \
-e "CONANEXILES_ServerSettings_ServerSettings_DisableBuildingAbandonment"="True" \
-e "CONANEXILES_ServerSettings_ServerSettings_EnablePurge"="True" \
-e "CONANEXILES_Engine_OnlineSubSystemSteam_ServerName"="AndargorPlayground" \
-e "CONANEXILES_Engine_OnlineSubSystemSteam_ServerPassword"="XXXX" \
-e "CONANEXILES_Game_RconPlugin_RconPassword"="XXXX" \
-e "CONANEXILES_Game_RconPlugin_RconPort"=32330 \
-e "CONANEXILES_SERVER_TYPE"="pvp" \
-v /local2/conanexiles:/conanexiles --name conanexiles --security-opt apparmor=docker-ptrace --restart=always alinmear/docker-conanexiles
```

**Comment by Andargor** [comment] 2019-01-26 23:04
I deleted the manifest file and it seems the update worked this time.

```bash
/conanexiles/steamapps/appmanifest_443030.acf
```

Perhaps this should be deleted every time during conanexilesUpdate? I will keep an eye on the server for the next few days.

**Comment by TBK** [comment] 2019-02-05 22:31
I have not experienced the issue you describe.

Have you experienced it since using your workaround?

**Comment by Andargor** [comment] 2019-02-05 23:04
Not since I reported it. I'll reopen if it happens again.

**Comment by sephallen** [comment] 2019-02-09 14:00
I'm still getting this.
Deleting the appmanifest file fixes it until the next update.

**Comment by Andargor** [comment] 2019-02-09 14:34
Reopening in case others have the same issue. I have not seen it again, although there doesn't seem to have been a game update for me recently.

**Comment by TBK** [comment] 2019-02-09 23:44
@sephallen When did you build your image?

**Comment by sephallen** [comment] 2019-02-10 00:48
@TBK 6 weeks ago.

**Comment by TBK** [comment] 2019-02-10 21:16
From my research it is related to steamcmd. I am looking into an alternative.

**Comment by hardiselg** [comment] 2019-02-28 18:18
After update my conan server will not restart. It keeps saying 

`Warning: Update seems to have failed. Installed build (0) does not match available build (3530875).`

even after applying the updates and removing the 
`appmanifest_443030.acf` file.

Is anyone else having this problem?

**Comment by TBK** [comment] 2019-03-26 15:18
@sephallen did you try what hardiselg suggested?

**Comment by sephallen** [comment] 2019-03-27 15:03
@TBK yes I did, and it worked for me too!

**Comment by TBK** [comment] 2019-03-28 15:24
Super, I am guessing it is a user or permissions issue. Would be great if anybody else experiences this could make a dump of the permissions before and after using hardiselg solution.

**Comment by sephallen** [comment] 2019-03-29 07:52
@TBK it could well be a permission error, but I don't believe caused by the user.

I say this because my docker has started showing the same symptoms again as of the most recent Conan server update.

**Comment by hardiselg** [comment] 2019-04-01 12:44
Automated update does not work for me, so basically I do the update manually every time as I described [above.](https://github.com/alinmear/docker-conanexiles/issues/34#issuecomment-468379849)
Essentially what happens is it does the update, or ties to do it. And then the version check fails. After that the server will be restarted and the same cycle happens.

After the validation I get this error:
`Error! App '443030' state is 0x406 after update job.`

**Comment by alinmear** [comment] 2020-06-20 08:55
app_update 443030 validate has been already added to the install.txt. Closing this issue

**Closed by alinmear** 2020-06-20 08:55 UTC
