### ISSUE TITLE
Server ignoring settings

### ISSUE THREAD

**Issue by IF-Adin** [alinmear/docker-conanexiles#47] opened 2020-10-19 20:37 UTC
IIf have this in my docker-compose.yml:

      - "CONANEXILES_ServerSettings_ServerSettings_AdminPassword=test"
      - "CONANEXILES_ServerSettings_ServerSettings_IsBattlEyeEnabled=False"

And i checked in the container, it did actually add it into the config, but it will not make me admin, regardless of what password i set. It also still attempts to use BattleEye.

**Comment by dr-waterstorm** [comment] 2021-01-01 17:04
I can confirm this issue.

It's strange however. The server log tells me that it reads the custom ServerSettings.ini and shows me the correct path. Also the content is correct. But it does not prefer those values over whatever is set in DefaultServerSettings.ini.
If I change the settings in the default file, it uses those instead of the provided custom ones.

Does anyone also have this issue and may know a solution?

Thank you!

**Comment by Flow86** [comment] 2021-01-19 13:54
Hi,
*False* must be *false* (case sensitive!)
thats working for me then

**Comment by alinmear** [comment] 2021-03-26 21:48
The Problem occurred because of a problem within the entrypoint.sh. Config Path was not correct, so env Variables had no effect. Fixed within master

**Closed by alinmear** 2021-03-26 21:48 UTC
